package com.example.data.repository

import android.content.Context
import android.media.MediaMetadataRetriever
import android.util.Log
import com.example.audio.AudioPlayer
import com.example.audio.AudioRecorder
import com.example.data.api.GapGptService
import com.example.data.database.VoiceMessage
import com.example.data.database.VoiceMessageDao
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext
import java.io.File
import java.io.IOException

class VoiceChatRepository(
    private val context: Context,
    private val dao: VoiceMessageDao,
    private val settingsRepository: SettingsRepository,
    private val audioPlayer: AudioPlayer,
    private val audioRecorder: AudioRecorder
) {
    private val apiService = GapGptService()

    val allMessages: Flow<List<VoiceMessage>> = dao.getAllMessagesFlow()

    // Create a stable directory inside internal storage for permanent voice notes
    private val voiceDir: File by lazy {
        File(context.filesDir, "voices").apply {
            if (!exists()) {
                mkdirs()
            }
        }
    }

    // Temporary file for recording
    private var currentRecordingFile: File? = null

    fun startRecording() {
        val file = File(context.cacheDir, "recording_${System.currentTimeMillis()}.m4a")
        currentRecordingFile = file
        audioRecorder.start(file)
    }

    fun getMaxAmplitude(): Int {
        return audioRecorder.getMaxAmplitude()
    }

    /**
     * Stops recording, saves the user message to Room, and returns the message or null if failed.
     */
    suspend fun stopRecordingAndSave(): VoiceMessage? = withContext(Dispatchers.IO) {
        val durationMs = audioRecorder.stop()
        val file = currentRecordingFile
        if (file == null || !file.exists() || durationMs < 300) {
            Log.e("VoiceChatRepository", "Recording file is null, empty or too short. Duration: ${durationMs}ms")
            return@withContext null
        }

        // Copy recording from cache directory to permanent voice directory so it's archived
        val permanentFile = File(voiceDir, "user_${System.currentTimeMillis()}.m4a")
        try {
            file.copyTo(permanentFile, overwrite = true)
        } catch (e: Exception) {
            Log.e("VoiceChatRepository", "Failed to copy recorded voice to permanent storage", e)
            return@withContext null
        }

        val message = VoiceMessage(
            role = "user",
            audioPath = permanentFile.absolutePath,
            durationMs = durationMs,
            transcript = "صدا در حال بارگذاری..." // Placeholder until transcribed
        )
        dao.insertMessage(message)
        
        // Return a fresh copy of the message with the assigned autogenerated ID if possible, or just the original
        // Let's query the database to find our inserted item
        val allMsg = dao.getAllMessagesList()
        val savedMsg = allMsg.lastOrNull { it.audioPath == permanentFile.absolutePath } ?: message
        savedMsg
    }

    /**
     * Performs Whisper transcription, updates Room, then queries chat, TTS, and archives the AI response.
     */
    suspend fun processUserMessage(userMsg: VoiceMessage, onError: (String) -> Unit) = withContext(Dispatchers.IO) {
        try {
            val apiKey = settingsRepository.getApiKey()
            val baseUrl = settingsRepository.getBaseUrl()
            
            if (apiKey.isEmpty()) {
                throw IOException("کلید API تعریف نشده است. لطفا به بخش تنظیمات بروید.")
            }

            // 1. Transcribe recorded audio
            val audioFile = File(userMsg.audioPath)
            val whisperModel = settingsRepository.getWhisperModel()
            
            val transcription = try {
                apiService.transcribe(apiKey, baseUrl, whisperModel, audioFile)
            } catch (e: Exception) {
                val fallbackModel = if (whisperModel == "gapgpt/whisper-1") "whisper-1" else "gapgpt/whisper-1"
                Log.w("VoiceChatRepository", "First Whisper transcription failed ($whisperModel), trying fallback ($fallbackModel)", e)
                try {
                    apiService.transcribe(apiKey, baseUrl, fallbackModel, audioFile)
                } catch (e2: Exception) {
                    Log.e("VoiceChatRepository", "Both Whisper models failed", e2)
                    throw IOException("خطا در فهمیدن صدای شما: ${e2.localizedMessage ?: "ارتباط قطع شد"}")
                }
            }

            // Update user message with transcript
            val updatedUserMsg = userMsg.copy(transcript = transcription)
            dao.insertMessage(updatedUserMsg)

            // 2. Get AI Chat Completion
            val history = dao.getAllMessagesList()
            val chatModel = settingsRepository.getChatModel()
            val systemPrompt = settingsRepository.getSystemPrompt()

            val replyText = try {
                apiService.askAi(apiKey, baseUrl, chatModel, systemPrompt, history)
            } catch (e: Exception) {
                Log.e("VoiceChatRepository", "AI Chat completion failed", e)
                throw IOException("خطا در پاسخ هوش مصنوعی: ${e.localizedMessage ?: "ارتباط قطع شد"}")
            }

            // 3. Generate Speech (TTS)
            val ttsModel = settingsRepository.getTtsModel()
            val voice = settingsRepository.getTtsVoice()
            val assistantAudioFile = File(voiceDir, "assistant_${System.currentTimeMillis()}.mp3")

            try {
                apiService.generateSpeech(apiKey, baseUrl, ttsModel, voice, replyText, assistantAudioFile)
            } catch (e: Exception) {
                Log.e("VoiceChatRepository", "TTS speech generation failed", e)
                throw IOException("خطا در تولید صدای هوش مصنوعی: ${e.localizedMessage ?: "ارتباط قطع شد"}")
            }

            // Calculate generated audio file duration
            val durationMs = getAudioDurationMs(assistantAudioFile)

            // 4. Save Assistant message in Room
            val assistantMsg = VoiceMessage(
                role = "assistant",
                audioPath = assistantAudioFile.absolutePath,
                durationMs = durationMs,
                transcript = replyText
            )
            dao.insertMessage(assistantMsg)

            // 5. Play the generated speech immediately for her mother to hear
            withContext(Dispatchers.Main) {
                audioPlayer.play(assistantAudioFile.absolutePath)
            }

        } catch (e: Exception) {
            Log.e("VoiceChatRepository", "Processing turn failed", e)
            withContext(Dispatchers.Main) {
                onError(e.message ?: "خطایی در برقراری ارتباط رخ داد.")
            }
        }
    }

    /**
     * Extract audio duration in milliseconds.
     */
    private fun getAudioDurationMs(file: File): Long {
        val retriever = MediaMetadataRetriever()
        var duration = 0L
        try {
            retriever.setDataSource(file.absolutePath)
            val time = retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION)
            duration = time?.toLong() ?: 0L
        } catch (e: Exception) {
            Log.e("VoiceChatRepository", "Could not retrieve audio duration for ${file.name}", e)
            // fallback to file size estimate (roughly 8000 bytes per second for tts speech)
            duration = (file.length() / 8).coerceAtLeast(1000L)
        } finally {
            try {
                retriever.release()
            } catch (e: Exception) {
                // Ignore
            }
        }
        return duration
    }

    suspend fun clearArchive() = withContext(Dispatchers.IO) {
        // Stop any playing audio
        withContext(Dispatchers.Main) {
            audioPlayer.stop()
        }
        
        // Delete physical files
        try {
            voiceDir.listFiles()?.forEach { file ->
                file.delete()
            }
        } catch (e: Exception) {
            Log.e("VoiceChatRepository", "Failed to delete archived voice files", e)
        }

        // Clear Room database
        dao.clearAllMessages()
    }

    suspend fun generateAndPlaySample(voice: String, text: String, onFinished: (String?) -> Unit) = withContext(Dispatchers.IO) {
        val sampleFile = File(context.cacheDir, "sample_voice_$voice.mp3")
        if (sampleFile.exists() && sampleFile.length() > 100) {
            withContext(Dispatchers.Main) {
                audioPlayer.play(sampleFile.absolutePath)
                onFinished(null)
            }
            return@withContext
        }

        try {
            val apiKey = settingsRepository.getApiKey()
            val baseUrl = settingsRepository.getBaseUrl()
            val ttsModel = settingsRepository.getTtsModel()
            apiService.generateSpeech(apiKey, baseUrl, ttsModel, voice, text, sampleFile)
            withContext(Dispatchers.Main) {
                audioPlayer.play(sampleFile.absolutePath)
                onFinished(null)
            }
        } catch (e: Exception) {
            Log.e("VoiceChatRepository", "Failed to generate sample voice for $voice", e)
            withContext(Dispatchers.Main) {
                onFinished("خطا در بارگذاری نمونه صدا: ${e.localizedMessage}")
            }
        }
    }
}
